### ISSUE TITLE
DescribeSensor requests returns some out of order/misnamed members

### ISSUE THREAD

**Issue by daf** [asascience-open/ncSOS#119]
XML Schemas allow ordering of elements to be significant.   This issue will capture all the noticed inconsistencies with the spec as reported in the SECOORA report.
- [x] `gml:description` must precede `gml:name`
- [x] in `sml:contactInfo/sml:address`, `sml:country` must precede `sml:electronicEmailAddress`
- [x] in `sml:contactInfo`, `phone` and `address` must be `sml:` prefixed
- [x] in `sml:outputs/sml:OutputList`, `sml:Quantity` -> `swe:Quantity` and `sml:uom` -> `swe:uom`
- [x] in `sml:ComponentList/sml:component/sml:System/sml:documentation`, urls must be html encoded (aka `&` -> `&amp;`)

**Comment by abirger** [comment]
I am re-opening the issue as the test of the ncSOS v1.2.2 reveals a similar XML Schema violation of the order of elements, i.e.:

in `<sml:contactInfo>` list the `<sml:phone>` parameter shall precede `<sml:address>`
