### ISSUE TITLE
Thredds 4.3 with java 1.8 does not work with NCSOS

### ISSUE THREAD

**Issue by birdage** [asascience-open/ncSOS#160]
I tested java 1.8 with ncsos using thredds 4.3 and ncsos does not work with getObs requests (works for get caps). i then moved to java 1.7 and it works, so it seems ncsos does not work with java 1.8

**Comment by kknee** [comment]
@cheryldmorse does Java 1.8 with ncSOS and TDS 4.5 work okay?

**Comment by cheryldmorse** [comment]
@kknee it is still an issue with ncSOS and TDS 4.5

**Comment by cheryldmorse** [comment]
Fixed with checkins da55722 / 448efe8
