### ISSUE TITLE
Units in the descrieSensor response contain invalid characters

### ISSUE THREAD

**Issue by cheryldmorse** [asascience-open/ncSOS#161]
The  ‘swe:uom code=<>’  elements are not always passing schema validation because the ‘code’ value must be of ‘swe:UomSymbol’ type, which prohibits the use of colons, spaces, linefeeds and tabs. Currently, ncSOS is simply copying the value of the "units" attribute into the 'code.'

**Comment by abirger** [comment]
@cheryldmorse , ncSOS should either do some kind of encoding of the prohibited symbols (e.g. `<swe2:uom code="m%20s-1"/>`); or in more radical manner completely replace the `code` with a `udunits` URN like i52N does (then `<swe2:uom code="m s-1"/>` becomes `<swe2:uom xlink:href="urn:ogc:def:uom:udunits:2:m.s-1"/>`).
