### ISSUE TITLE
Enhance ncSOS to support QC flags

### ISSUE THREAD

**Issue by cheryldmorse** [asascience-open/ncSOS#162]

**Comment by lukecampbell** [comment]
I just finished up the IOOS DMAC Webinar about this very thing.

**Comment by lukecampbell** [comment]
A good starting point is https://github.com/ioos/sos-guidelines/blob/409fa35aefe9257e82f22cb7f060beca19033f54/template/milestone1.0/SWE-SingleStation-TimeSeriesProfile_QC.xml

We're still trying to figure out how to represent the flag information though.

**Comment by kknee** [comment]
Based on recommendations for QARTOD implementation in netCDF, ncSOS already provides offerings for variables which represent quality flags.
