### ISSUE TITLE
Wrong <sml:location> element in a DescribeSensor response

### ISSUE THREAD

**Issue by abirger** [asascience-open/ncSOS#167]
A DescribeSensor response may contain wrongly placed and/or badly formatted <sml:location> element. 
For example, the [CariCOOS SWAN DescribeSensor response for `Grid0` "station"](http://dm2.caricoos.org/thredds/sos/content/swan/Historical/201502260000.nc?request=DescribeSensor&service=SOS&version=1.0.0&procedure=urn%3Aioos%3Astation%3Ancsos%3AGrid0&outputFormat=text%2Fxml%3Bsubtype%3D%22sensorML%2F1.0.1%2Fprofiles%2Fioos_sos%2F1.0%22) returns wrong <sml:location>:

 * element <gml:boundedBy> cannot appear inside <sml:location>; instead, one of '{"http://www.opengis.net/gml":Point, "http://www.opengis.net/gml":_Curve}' is expected
 * attribute `srsName` is not allowed to appear in element <gml:boundedBy>
 * the coordinates <gml:lowerCorner> and <gml:upperCorner> must be enclosed into <gml:Envelope>.

The following outline of the DescribeSensor response depicts the error:

```
<sml:SensorML xmlns:sml="http://www.opengis.net/sensorML/1.0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:gml="http://www.opengis.net/gml" xmlns:swe="http://www.opengis.net/swe/1.0.1" xsi:schemaLocation="http://www.opengis.net/sensorML/1.0.1 http://schemas.opengis.net/sensorML/1.0.1/sensorML.xsd" version="1.0.1">
    <sml:capabilities name="ioosServiceMetadata"> [13 lines]
    <sml:member>
        <sml:System>
            <gml:description>no description</gml:description>
            <gml:name>urn:ioos:station:ncsos:Grid0</gml:name>
            <gml:boundedBy>
                <gml:Envelope srsName="http://www.opengis.net/def/crs/EPSG/0/4326">
                    <gml:lowerCorner>17.0 -68.0</gml:lowerCorner>
                    <gml:upperCorner>19.5 -64.0</gml:upperCorner>
                </gml:Envelope>
            </gml:boundedBy>
	<sml:identification> [18 lines]
            <sml:classification>
                <sml:ClassifierList> [31 lines]
            </sml:classification>
            <sml:capabilities name="observationTimeRange"> [8 lines]
            <sml:capabilities name="networkProcedures"> [8 lines]
            <sml:contact> [33 lines]
            <sml:documentation />
            <sml:history />
            <sml:location>
                <gml:boundedBy srsName="http://www.opengis.net/def/crs/EPSG/0/4326">
                    <gml:lowerCorner>17.0 -68.0</gml:lowerCorner>
                    <gml:upperCorner>19.5 -64.0</gml:upperCorner>
                </gml:boundedBy>
            </sml:location>
            <sml:components> [67 lines]
	        </sml:System>
    </sml:member>
</sml:SensorML>
```
The [CariCOOS SWAN DescribeSensor response for `network-all`](http://dm2.caricoos.org/thredds/sos/content/swan/Historical/201502260000.nc?request=DescribeSensor&service=SOS&version=1.0.0&procedure=urn%3Aioos%3Anetwork%3Ancsos%3Aall&outputFormat=text%2Fxml%3Bsubtype%3D%22sensorML%2F1.0.1%2Fprofiles%2Fioos_sos%2F1.0%22) produces the similar error:

```
<sml:SensorML xmlns:sml="http://www.opengis.net/sensorML/1.0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:gml="http://www.opengis.net/gml" xmlns:swe="http://www.opengis.net/swe/1.0.1" xsi:schemaLocation="http://www.opengis.net/sensorML/1.0.1 http://schemas.opengis.net/sensorML/1.0.1/sensorML.xsd" version="1.0.1">
    <sml:capabilities name="ioosServiceMetadata"> [13 lines]
    <sml:member>
        <sml:System>
            <gml:description>No description found</gml:description>
            <gml:name>urn:ioos:network:ncsos:all</gml:name>
            <gml:boundedBy>
                <gml:Envelope srsName="http://www.opengis.net/def/crs/EPSG/0/4326">
                    <gml:lowerCorner>17.0 -68.0</gml:lowerCorner>
                    <gml:upperCorner>19.5 -64.0</gml:upperCorner>
                </gml:Envelope>
            </gml:boundedBy>
            <sml:identification> [18 lines]
            <sml:classification> [27 lines]
            <sml:capabilities name="observationTimeRange"> [8 lines]
            <sml:contact> [27 lines]
            <sml:documentation />
            <sml:history />
            <sml:components>
                <sml:ComponentList>
                    <sml:component name="Grid0">
                        <sml:System>
                            <sml:identification>
                                <sml:IdentifierList>
                                    <sml:identifier name="stationID">
                                        <sml:Term definition="http://mmisw.org/ont/ioos/definition/stationID">
                                            <sml:value>urn:ioos:station:ncsos:Grid0</sml:value>
                                        </sml:Term>
                                    </sml:identifier>
                                    <sml:identifier name="shortName"> [4 lines]
                                    <sml:identifier name="longName"> [4 lines]
                                </sml:IdentifierList>
                            </sml:identification>
                            <sml:capabilities name="observationTimeRange"> [8 lines]
                            <sml:location>
                                <gml:boundedBy srsName="http://www.opengis.net/def/crs/EPSG/0/4326">
                                    <gml:lowerCorner>17.0 -68.0</gml:lowerCorner>
                                    <gml:upperCorner>19.5 -64.0</gml:upperCorner>
                                </gml:boundedBy>
                            </sml:location>
                            <sml:outputs> [23 lines]
                        </sml:System>
                    </sml:component>
                </sml:ComponentList>
            </sml:components>
        </sml:System>
    </sml:member>
</sml:SensorML>
```

**Comment by cheryldmorse** [comment]
@abirger The two options listed for sml:location that you list above {"http://www.opengis.net/gml":Point, "http://www.opengis.net/gml":_Curve} don't apply because this is a gridded dataset. What should be used? The old templates in the google archive (ioostech/trunk/templates/1.0/DescribeSensor/Network/.svn/text-base/DescribeSensor-Network-All-Grid-sensorML1.0.1.xml.svn-base) use gml:boundedBy as well.

**Comment by abirger** [comment]
@cheryldmorse , the first bullet is the Oxygen's message about schema validation error - the DS schema prohibits <gml:boundedBy> from appearing in <sml:location>. The IOOS template for the DS-network response has never used <gml:boundedBy> in that context; the exact copy of the template from ioostech is now located at http://ioos.github.io/sos-guidelines/template/SML-DescribeSensor-Network/.

I believe that what put you to confusion is multiple appearance of the <sml:System> elements. However, there is an important difference: the <sml:System>/<sml:location> always refers to the network components (i.e. stations), and it always has point-type coordinates. By contrast, the <gml:boundedBy> is a part of the <sml:member>/<sml:System> element, which refers to the whole network of stations.

To illustrate the use of `location`, I made 3 snapshots of the DS-network response outlines for i52N v1.0, CariCOOS' ncSOS v1.2, and Maracoos' ncSOS v1.2.2, and put them next to each other. [You may see](https://docs.google.com/a/noaa.gov/document/d/1CSDtHt_6zUlVywL9jitrGTYw8Wk6N9PkCn-3rkAj3i8/edit?usp=sharing) that in the valid response the component must be presented as a platform and have a point-type coordinates; otherwise, the schema validation error is generated. If that is impossible, I guess that just leaving <sml:location> empty would be better than the use of the <gml:boundedBy> there - it would pass the schema validation, although it makes the ncSOS and i52N responses somewhat inconsistent.

**Comment by cheryldmorse** [comment]
@abirger I looked at the document that you sent and I see the validation error you are talking about. It makes sense to use the sml:location/sml:point for the Maracoos example but the file that you're using on CariCoos is gridded data and contains 250x400 different observation points. For gridded data, I don't see how we could fill out sml:location with a valid schema. What observation point would go in the sml:location/sml:point? 
The ioostech document that I mentioned earlier  was specifically for gridded data and I found a copy of it here: https://github.com/asascience-open/ncSOS/blob/master/examples/DescribeSensor-Grid-sensorML1.0.1.xml.  Since it has invalid schema I'll remove it from the examples folder.

**Comment by abirger** [comment]
@cheryldmorse , OK, now I understand what you were talking about. Yes, that example contains a lot of schema violations, so it is not the best example to follow. I also see your point (no pun intended) with the `<sml:location>`. I remember that there was a long discussion about the use of `<sml:location>` vs. `<sml:position>`, which is much more versatile but much more complex. The `<sml:location>` finally won because of the simplicity. Nobody could think at that moment that we would use SOS to serve gridded data.

Anyway, back from the historical digression. I think that we have two options of how to deal with the gridded data "location": (1) simply not report the location in `componentList` but leave empty `<sml:location/>` just for consistency with i52N, and (2) use `<sml:Component>` instead of `<sml:System>` just for gridded data as `<sml:Component>` allows bounding box:
```
            <sml:components>
                <sml:ComponentList>
                    <sml:component name="Grid0">
                        <sml:Component>
                            <gml:boundedBy>
                                <gml:Envelope>
                                    <gml:lowerCorner></gml:lowerCorner>
                                    <gml:upperCorner></gml:upperCorner>
                                </gml:Envelope>
                            </gml:boundedBy>
```
Option 1 is kind of a stretcher but not a far-fetched one, and it is a very simple solution that does not generally change the template. Option 2 is more rigorous but may have more consequences as it changes the basic template. For a quick fix, I would lean towards Option 1, but I believe that we should mark this issue for more thorough discussion - it may be worth it to get rid of `<sml:component>/<sml:System>` altogether and switch over to `<sml:component>/<sml:Component>` instead...

**Comment by abirger** [comment]
@cheryldmorse , BTW, there is a fantastic [SensorML v1.0.1 Schema Browser tool](http://www.botts-inc.com/SensorMLv1.0_Browser.html) available for SensorML schema exploration.

**Comment by cheryldmorse** [comment]
The ```sml:location``` for gridded datasets will be set to ```<sml:location/>``` (option 1 above). Option 2 is documented in [this issue.](https://github.com/ioos/ioos-sos-issues-generic/issues/1)
