### ISSUE TITLE
Does ncSOS work on TDS 4.6?

### ISSUE THREAD

**Issue by rsignell-usgs** [asascience-open/ncSOS#168]
Has anyone tried ncSOS on TDS 4.6 yet?

**Comment by pacioos** [comment]
Now that TDS 4.6.1 was released yesterday as stable, I'm also wondering the same question... Any word on this yet ncSOS folks? Thanks! --John Maurer

**Comment by cheryldmorse** [comment]
@rsignell-usgs, @pacioos - Version [1.2] (https://github.com/asascience-open/ncSOS/releases/tag/v1.2)  works on TDS 4.6
