### ISSUE TITLE
Add ability to generate geoJSON output from ncSOS servcie

### ISSUE THREAD

**Issue by kknee** [asascience-open/ncSOS#169]

**Comment by cheryldmorse** [comment]
Added a response format of "text/json" - #184

Here is an example: http://sos.maracoos.org/pre/sos/ncei11/NODC_timeSeries_template_v1.1_2016-06-15_133715.075689.nc?request=GetObservation&service=SOS&version=1.0.0&responseFormat=text/json&offering=urn:ioos:station:NCEI:Mooring1&observedProperty=sea_water_temperature
