### ISSUE TITLE
Wrong observedProperty name

### ISSUE THREAD

**Issue by abirger** [asascience-open/ncSOS#174]
In ncSOS v1.2.2 responses, a wrong observedProperty name `wind_direction` is used instead of the CF Standard name (either `wind_to_direction` or `wind_from_direction`). The `wind_direction` is not in IOOS vocabulary either.

**Comment by cheryldmorse** [comment]
This is an issue with the underlying netCDF. NcSOS reads the standard name from the NC file and sets the observed property accordingly. The NC file needs to be updated to set the correct standard name.
