### ISSUE TITLE
Determine desired behavior when ncSOS encounters featureType=grid

### ISSUE THREAD

**Issue by dpsnowden** [asascience-open/ncSOS#176]
How should ncSOS behave for this situation?  This is  a discussion item for future releases.

**Comment by cheryldmorse** [comment]
@abirger @dpsnowden @kknee Does anyone have any ideas on how to proceed with this ticket? Are there any new GetObservation templates for the grid feature type? Ticket #166 also relates to grids.

**Comment by kknee** [comment]
@mwengren can you chime in here given all your recent work with SOS?

**Comment by cheryldmorse** [comment]
ncSOS will return data for gridded sets when the user specifies the responseFormat of ```text/xml;subtype="om/1.0.0"``` and the latitude/longitude of the desired location For the response format of ```text/xml;subtype="om/1.0.0/profiles/ioos_sos/1.0"``` we could require that the user specify the desired latitude /longitude and then return the data following the time series schema. @kknee, @dpsnowden, @mwengren, @abirger, @jbosch-noaa - What do you guys think?

**Comment by kknee** [comment]
@cheryldmorse sounds good to me.  Thoughts from others?

**Comment by dpsnowden** [comment]
Two questions.  First, I'm not sure I understand the differences between the two examples that relate to the different responseFormats.  I think behavior should be the same if someone requests a single lat/lon from a gridded data set, it's just the format of the response that might be different, right?  

Second, what about depth.  If someone queries a 4d data set and only specifies the lat/lon, will they get a timeSeriesProfile in return?

**Comment by abirger** [comment]
@dpsnowden , on the 1st question I would assume that only the responseFormat of ` text/xml;subtype="om/1.0.0/profiles/ioos_sos/1.0"` is required in the IOOS SOS v1.0 templates, while the responseFormat of `text/xml;subtype="om/1.0.0"` is "non-conventional". 

On the 2nd question, just out of general consideration that the identical requests to i52N and ncSOS must trigger identical response, the request to ncSOS with the IOOS SOS v1.0 responseFormat should generate either type of response but only one, i.e. either timeSeries or timeSeriesProfile but they should never interchange. The timeSeries is as good as the timeSeriesProfile, we just have to choose one.
By contrast, the "non-conventional" responseFormat has no such limitation, and can generate any kind of response, including interchangeable timeSeries and timeSeriesProfile depending on the request format. It will be additional feature beyond the scope of the IOOS SOS; it may be useful or not.

**Comment by cheryldmorse** [comment]
@dpsnowden @abirger - 
Yes, it's just the format of the data that would change when requesting the different response formats. 

Right now when the user specifies latitude/longitude or latitude/longitude/depth and the response format of ```text/xml;subtype="om/1.0.0"``` then the data is returned for gridded datasets. We could require that for 3D datasets the user specify the latitude, longitude AND depth. That way accessing a gridded dataset would always return just a timeseries. This would be the similar to how ncSOS already behaves when the "non-conventional" response format is specified.

**Comment by cheryldmorse** [comment]
@abirger, @dpsnowden,  @mwengren, @kknee -  Is everyone ok with requiring the depth to be specified for 3D datasets and then always returning a timeSeries?

**Comment by abirger** [comment]
@cheryldmorse , I have no objection to that as far as i52N's responds to such request in a similar manner.

**Comment by dpsnowden** [comment]
I would prefer that we don't require depth but provide the option. Time series profile is well defined so it makes sense to allow the user to request both with and without depth. 


Cheers,
Derrick 

240-778-9129




On Mon, Jan 9, 2017 at 5:46 PM -0500, "abirger" <notifications@github.com> wrote:












@cheryldmorse , I have no objection to that as far as i52N's responds to such request in a similar manner.

**Comment by cheryldmorse** [comment]
- Updated ncSOS to return a timeSeries for gridded netCDF datasets when the latitude/longitude (and depth if 3d) are specified.
- Updated ncSOS to return a timeSeriesProfile for 3D gridded sets when the latitude/longitude is specified but the depth is not.

**TimeSeries**
[ 2D Grid](http://sos.maracoos.org/pre/sos/test/hycom_3d_r1_2016122200.nc?request=GetObservation&service=SOS&version=1.0.0&offering=urn:ioos:station:ncsos:Grid0&observedProperty=http://mmisw.org/ont/fake/parameter/water_u&responseFormat=text%2Fxml%3Bsubtype%3D%22om%2F1.0.0%2Fprofiles%2Fioos_sos%2F1.0%22&longitude=260&latitude=1&depth=0)
[3D Grid](http://sos.maracoos.org/pre/sos/test/hfradar_uswc20170116.nc?request=GetObservation&service=SOS&version=1.0.0&responseFormat=text%2Fxml%3Bsubtype%3D%22om%2F1.0.0%2Fprofiles%2Fioos_sos%2F1.0%22&longitude=-123&latitude=37&offering=urn:ioos:station:ncsos:Grid0&observedProperty=surface_eastward_sea_water_velocity)

**TimeSeriesProfile**
[3D Grid](http://sos.maracoos.org/pre/sos/test/hycom_3d_r1_2016122200.nc?request=GetObservation&service=SOS&version=1.0.0&offering=urn:ioos:station:ncsos:Grid0&observedProperty=http://mmisw.org/ont/fake/parameter/water_u&responseFormat=text%2Fxml%3Bsubtype%3D%22om%2F1.0.0%2Fprofiles%2Fioos_sos%2F1.0%22&longitude=260&latitude=1)
