### ISSUE TITLE
KVP parameter keys should be case insensitive

### ISSUE THREAD

**Issue by shane-axiom** [asascience-open/ncSOS#177]
The OGC OWS 1.1 spec requires that GET KVP keys be allowed to be in any case. See section 11.5.2 of the [OWS 1.1/06-121r3 spec](http://portal.opengeospatial.org/files/?artifact_id=20040).

> 11.5.2 Capitalization
> The capitalization of parameter names when KVP encoded shall be case insensitive,
> meaning that parameter names may have mixed case or not.
> EXAMPLES The “request” parameter name could be REQUEST, request, Request, or ReQuEsT.

However, when testing against version 1.2.1 of ncSOS, this doesn't seem to be the case (using PacIOOS as an example):

http://oos.soest.hawaii.edu/thredds/sos/pacioos/aws/himbagg?service=SOS&version=1.0.0&request=GetObservation&observedProperty=http%3A%2F%2Fmmisw.org%2Font%2Fcf%2Fparameter%2Fair_temperature&offering=urn%3Aioos%3Anetwork%3Aorg.pacioos%3Aall&procedure=urn%3Aioos%3Astation%3Aorg.pacioos%3Ahimb_weather_tower&responseFormat=text%2Fxml%3Bsubtype%3D%22om%2F1.0.0%2Fprofiles%2Fioos_sos%2F1.0%22

An error comes back stating that the `observedProperty` is missing when it's not. Instead, ncSOS seems to require a lowercase `observedproperty` parameter instead, which is in violation of the OGC spec and inconsistent with the error message.

With a lowercase `observedproperty`, the request works:

http://oos.soest.hawaii.edu/thredds/sos/pacioos/aws/himbagg?service=SOS&version=1.0.0&request=GetObservation&observedproperty=http%3A%2F%2Fmmisw.org%2Font%2Fcf%2Fparameter%2Fair_temperature&offering=urn%3Aioos%3Anetwork%3Aorg.pacioos%3Aall&procedure=urn%3Aioos%3Astation%3Aorg.pacioos%3Ahimb_weather_tower&responseFormat=text%2Fxml%3Bsubtype%3D%22om%2F1.0.0%2Fprofiles%2Fioos_sos%2F1.0%22

From spot checking GetObservation requests ncSOS seems to care about the case of `service`, `version`, `request`, `offering`, and `observedProperty`, and doesn't care about the case of `offering` or `responseFormat`. I didn't check the other requests.

**Comment by cheryldmorse** [comment]
Confirmed with pacIOOS that this is fixed in Version 1.3
