### ISSUE TITLE
UNKNOWN used instead of Date Format in GetCapabilities

### ISSUE THREAD

**Issue by lance-axiom** [asascience-open/ncSOS#179]
In the GetCapabilities request when the dateRange for an ObservationOffering is not set it uses "UNKNOWN" like below. 

```
<sos:time>
     <gml:TimePeriod>
           <gml:beginPosition>UNKNOWN</gml:beginPosition>  
           <gml:endPosition>UNKNOWN</gml:endPosition>
     </gml:TimePeriod>
</sos:time>
```

This should instead be:

```
<sos:time>
     <gml:TimePeriod>
         <gml:beginPosition indeterminatePosition="unknown"/>
         <gml:endPosition indeterminatePosition="unknown"/>
     </gml:TimePeriod>
</sos:time>
```

This error can be found in the code at:
https://github.com/asascience-open/ncSOS/blob/da557220f30a8796ef0d35ee9c8950a6afa69f56/src/main/java/com/asascience/ncsos/outputformatter/gc/GetCapsFormatter.java#L342

Below is the ncSOS request where this error was found:
http://tds.secoora.org/thredds/sos/fldep.redbaypoint..nc?service=SOS&version=1.0.0&request=GetCapabilities

**Comment by cheryldmorse** [comment]
Fix will be included in the 1.4 release
