### ISSUE TITLE
Maven Repo updated?

### ISSUE THREAD

**Issue by lesserwhirls** [asascience-open/ncSOS#180]
Greetings!

We've been looking into bundling ncSOS the THREDDS Data Server war file we at Unidata release, much like we do with ncWMS and ncISO, and it appears that this would be very straight forward (you've made it very easy - awesome!). However, I was wondering if your plan is still to post artifacts to a maven repository, as discussed in asascience-open/ncSOS#11? I ask because the last artifact was a 1.0 SNAPSHOT release, unless there is a new repository you are publishing to?

Thanks!

**Comment by cheryldmorse** [comment]
@lesserwhirls  That would be great! I'll get the newest build up on the maven repo ASAP and we will definitely make sure to push all future releases there as well. Thanks!

**Comment by lesserwhirls** [comment]
Hi @cheryldmorse - I was just wondering if you had a chance to post the artifact to a maven repo. I checked the repo in the pom file (http://geo.asascience.com/nexus/content/repositories/snapshots/) but I get a 404. Thanks!

**Comment by cheryldmorse** [comment]
@lesserwhirls Sorry for the delay but we now have a new maven repo setup. The new repo is [here](Maven.asascience.com )

**Comment by cheryldmorse** [comment]
@lesserwhirls I just noticed that there is an issue accessing that repo from outside our network. I'll let you know as soon as we have access opened up

**Comment by cheryldmorse** [comment]
This is all set now.

**Comment by lesserwhirls** [comment]
Thank you @cheryldmorse!
