### ISSUE TITLE
Very Large Datasets cause error in calcBounds()

### ISSUE THREAD

**Issue by birdage** [asascience-open/ncSOS#2]
when using an extremely large data file (over 500 station, 1400 enteries per station) calcbounds() hangs possible due to the large amount of data. It is quick to start, after 460 stations it slows down (getting start and end date manually)

currently investigating the issue

**Comment by kknee** [comment]
based on comments above this is wrapped in an exception and is not causing ncsos to crash.  Closing for now, can revisit if this becomes an issue.
