### ISSUE TITLE
"All Sensors" procedure

### ISSUE THREAD

**Issue by CowanSM** [asascience-open/ncSOS#66]
Add support for a procedure that returns all sensors for a station. This would help consolidate the CSVs for "text/xml;subtype="om/1.0.0/profiles/ioos_sos/1.0" responses. Would probably, need to touch each request in order to be complete.

**Comment by cheryldmorse** [comment]
Added the ability to get all observed properties with one request. Set ```observedProperty=all```and all properties will be returned. This will be included in version 1.4
