### ISSUE TITLE
Update xml node order in describe sensor

### ISSUE THREAD

**Issue by birdage** [asascience-open/ncSOS#89]

**Comment by kknee** [comment]
anyone have a recollection of what order was desired?

**Comment by kknee** [comment]
with no response to the last couple of pokes, closing this.

**Comment by kwilcox** [comment]
This revolved around the XML elements being in the incorrect order which lead to DescibeSensor responses not validating against the SensorML schema. I'm pretty sure this was fixed and just never closed.
